// svelte/src/views/layouts/DefaultLayout.svelte
<script lang="ts">
  import TopAppBar, { Row, Section, Title } from "@smui/top-app-bar";
  import Drawer, { Content, AppContent } from "@smui/drawer";
  import List, { Item, Text, Graphic } from "@smui/list";
  import IconButton from "@smui/icon-button";
  import Button, { Label } from "@smui/button";
  import LinearProgress from "@smui/linear-progress";

  import SVGIcon from "../../components/SVGIcon.svelte";

  import {
    mdiMenu,
    mdiLogout,
    mdiOfficeBuilding,
    mdiRouterNetwork,
    mdiLan,
  } from "@mdi/js";

  import { Route } from "svelte-router-spa";
  import type { CurrentRoute } from "svelte-router-spa/types/components/route";

  import api from "../../api";

  export let currentRoute: CurrentRoute & { childRoute: CurrentRoute };
  export const params = {};

  const navs = [
    { link: "/builds", text: "Builds", icon: mdiOfficeBuilding },
    { link: "/switches", text: "Switches", icon: mdiRouterNetwork },
    { link: "/vis", text: "Visualization", icon: mdiLan },
  ];

  let drawerOpen = true;
  let isLoading = false;

  api.interceptors.request.use(
    (config) => {
      isLoading = true;
      return config;
    },
    (error) => {
      isLoading = false;
      return Promise.reject(error);
    }
  );

  api.interceptors.response.use(
    (response) => {
      isLoading = false;
      return response;
    },
    (error) => {
      isLoading = false;
      /* if (error.response.status && error.response.status === 401) {
          this.$store.dispatch(AUTH_LOGOUT);
          this.$router.push("/login");
        } */
      return Promise.reject(error);
    }
  );
</script>

<TopAppBar
  variant="fixed"
  style="background-color: #212125; z-index: 7; box-shadow: 0 2px 4px -1px rgb(0 0 0 / 20%), 0 4px 5px 0 rgb(0 0 0 / 14%), 0 1px 10px 0 rgb(0 0 0 / 12%);"
>
  <Row>
    <Section>
      <IconButton on:click={() => (drawerOpen = !drawerOpen)}>
        <SVGIcon icon={mdiMenu} />
      </IconButton>
      <Title>SwitchMap</Title>
    </Section>
    <Section align="end" toolbar>
      <Button variant="raised" color="primary">
        <Label>Sign out</Label>
        <SVGIcon icon={mdiLogout} />
      </Button>
    </Section>
  </Row>
  <LinearProgress indeterminate closed={!isLoading} style="z-index: 8;" />
</TopAppBar>

<Drawer variant="dismissible" bind:open={drawerOpen} style="padding-top: 68px;">
  <Content>
    <List>
      {#each navs as nav (nav.link)}
        <Item
          href={nav.link}
          activated={currentRoute.name.startsWith(nav.link)}
        >
          <Graphic aria-hidden="true"><SVGIcon icon={nav.icon} /></Graphic>
          <Text>{nav.text}</Text>
        </Item>
      {/each}
    </List>
  </Content>
</Drawer>

<AppContent class="app-content">
  <main class="main-content" style="padding-top: 68px;">
    <Route {currentRoute} {params} />
  </main>
</AppContent>

<style>
  * :global(.app-content) {
    flex: auto;
    overflow: auto;
    position: relative;
    flex-grow: 1;
  }

  .main-content {
    overflow: auto;
    /* padding: 80px 16px 16px; */
    height: 100%;
    box-sizing: border-box;
  }
</style>

// ui/src/views/layouts/DefaultLayout.vue
<template>
  <div id="layout" :v-bind="isLoading">
    <v-navigation-drawer v-model="drawer" app dark clipped floating>
      <v-list>
        <v-list-item-group>
          <v-list-item v-for="(nav, i) in navs" :key="i" :to="nav.link">
            <v-list-item-icon>
              <v-icon v-text="nav.icon"></v-icon>
            </v-list-item-icon>
            <v-list-item-content>
              <v-list-item-title v-text="nav.text"></v-list-item-title>
            </v-list-item-content>
          </v-list-item>
        </v-list-item-group>
      </v-list>
    </v-navigation-drawer>

    <v-app-bar app dark clipped-left>
      <v-app-bar-nav-icon @click.stop="drawer = !drawer" />
      <v-toolbar-title>
        SwitchMap
        <!-- <v-breadcrumbs :items="breadcrumbs" large></v-breadcrumbs> -->
      </v-toolbar-title>
      <v-spacer />
      <v-btn color="orange darken-1" @click="logout">
        Sign out
        <v-icon right>{{ mdiLogout }}</v-icon>
      </v-btn>
      <v-progress-linear
        :active="isLoading"
        :indeterminate="isLoading"
        absolute
        bottom
        color="orange accent-4"
      ></v-progress-linear>
    </v-app-bar>

    <v-main>
      <v-container fluid>
        <slot :is-loading="isLoading" />
      </v-container>
    </v-main>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "@vue/composition-api";

import {
  mdiLogout,
  mdiOfficeBuilding,
  mdiRouterNetwork,
  mdiLan,
  mdiCopyright,
} from "@mdi/js";

import { AUTH_LOGOUT } from "@/store/actions";

export default defineComponent({
  props: {
    isLoading: { type: Boolean, required: true },
  },

  setup() {
    const drawer = ref(true);
    const navs = [
      { link: "/builds", text: "Builds", icon: mdiOfficeBuilding },
      { link: "/switches", text: "Switches", icon: mdiRouterNetwork },
      { link: "/vis", text: "Visualization", icon: mdiLan },
    ];

    //breadcrumbs: [],

    return {
      drawer,
      navs,

      mdiLogout,
      mdiCopyright,
    };
  },

  methods: {
    logout: function () {
      this.$store.dispatch(AUTH_LOGOUT).then(() => {
        this.$router.push("/login");
      });
    },
  },

  /* created() {
    console.log(this.$route.path.split("/"));
    this.breadcrumbs = [
      {
        text: "SwitchMap",
        disabled: true,
      },
    ];
    const arr = this.$route.path.split("/");
    let href = `/${arr[1]}`;
    if (arr.length > 2) {
      for (let i = 2; i < arr.length; i++) {
        href = `${href}/${arr[i]}`;
        this.breadcrumbs.push({
          text: arr[i],
          disabled: href === this.$route.path,
          href: href,
        });
      }
    }
  }, */
});
</script>

<style>
/* .v-application ol,
.v-application ul {
  padding-left: 0;
}
.theme--dark.v-breadcrumbs .v-breadcrumbs__divider,
.theme--dark.v-breadcrumbs .v-breadcrumbs__item--disabled {
  color: white;
}
.v-breadcrumbs--large li,
.v-breadcrumbs--large li .v-icon {
  font-size: 1.25rem;
} */
</style>
